name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build aarch64 (linux/arm64) wheels
    steps:
      - name: "Checkout abetlen/llama-cpp-python"
        uses: actions/checkout@v4
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: 'v0.2.20'
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_SKIP: "*musllinux* pp*"
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_ARCHS: "aarch64"
        with:
          output-dir: wheelhouse

      - name: List wheelhouse contents
        run: ls -la wheelhouse/