name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - v0.2.23
          - v0.2.24
          - v0.2.25
          - v0.2.26
          - v0.2.27
          - v0.2.28
          - v0.2.29
          - v0.2.30
          - v0.2.31
          - v0.2.32
    steps:
      - name: Checkout abetlen/llama-cpp-python
        uses: actions/checkout@v4
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: '${{ matrix.version }}'
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_SKIP: "*musllinux* pp*"
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_ARCHS: "aarch64"
          CIBW_BUILD: "cp311-*"
        with:
          output-dir: wheelhouse/

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.version }}
          path: wheelhouse/*.whl

  prepare_deployment:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Create directory for wheels
        run: mkdir -p public/llama-cpp-python/

      - name: Create directory for wheels artifacts
        run: mkdir -p /tmp/wheels

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp/wheels

      - name: Move wheels
        run: mv /tmp/wheels/*/*.whl public/llama-cpp-python/

      - name: List wheels
        run: ls -la public/llama-cpp-python/

      - name: Make Python Package Index
        uses: girder/create-pip-index-action@main
        with:
          package_directory: public/llama-cpp-python/

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main

      - name: Add main index.html
        run: cp main/index.html public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
